# This workflow will do a clean install of node dependencies, run tests and lint across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 2021 build and test

on:
  push:
    paths:
      - "2021/**"
    branches: [ main ]
  pull_request:
    paths:
      - "2021/**"
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        working-directory: "2021"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn run test
    - name: Lint source
      run: yarn run lint
